// <auto-generated />
using System;
using System.Collections.Generic;
using CVA.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CVA.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(PostgresContext))]
    [Migration("20260108025020_AddPhoneNumber")]
    partial class AddPhoneNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CVA.Infrastructure.Postgres.DeveloperProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<bool>("OpenToWork")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("open_to_work");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("role");

                    b.PrimitiveCollection<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Verified")
                        .HasColumnType("integer")
                        .HasColumnName("verified");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("website");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience");

                    b.HasKey("Id");

                    b.ToTable("developer_profiles", (string)null);
                });

            modelBuilder.Entity("CVA.Infrastructure.Postgres.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DeveloperProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("developer_profile_id");

                    b.Property<string>("IconUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("icon_url");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("link_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.PrimitiveCollection<List<string>>("TechStack")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tech_stack");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperProfileId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("CVA.Infrastructure.Postgres.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("photo");

                    b.PrimitiveCollection<List<string>>("Skills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("skills");

                    b.Property<string>("SummaryInfo")
                        .HasColumnType("text")
                        .HasColumnName("summary_info");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CVA.Infrastructure.Postgres.WorkExperienceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("company");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DeveloperProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("developer_profile_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("role");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.PrimitiveCollection<List<string>>("TechStack")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tech_stack");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperProfileId");

                    b.ToTable("work_experiences", (string)null);
                });

            modelBuilder.Entity("CVA.Infrastructure.Postgres.DeveloperProfileEntity", b =>
                {
                    b.OwnsOne("CVA.Infrastructure.Postgres.LocationEntity", "Location", b1 =>
                        {
                            b1.Property<Guid>("DeveloperProfileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.HasKey("DeveloperProfileEntityId");

                            b1.ToTable("developer_profiles");

                            b1.WithOwner()
                                .HasForeignKey("DeveloperProfileEntityId");
                        });

                    b.OwnsOne("CVA.Infrastructure.Postgres.SocialLinksEntity", "SocialLinks", b1 =>
                        {
                            b1.Property<Guid>("DeveloperProfileEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("GitHub")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("git_hub");

                            b1.Property<string>("LinkedIn")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("linked_in");

                            b1.Property<string>("Telegram")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("telegram");

                            b1.Property<string>("Twitter")
                                .HasMaxLength(255)
                                .HasColumnType("character varying(255)")
                                .HasColumnName("twitter");

                            b1.HasKey("DeveloperProfileEntityId");

                            b1.ToTable("developer_profiles");

                            b1.WithOwner()
                                .HasForeignKey("DeveloperProfileEntityId");
                        });

                    b.Navigation("Location");

                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("CVA.Infrastructure.Postgres.ProjectEntity", b =>
                {
                    b.HasOne("CVA.Infrastructure.Postgres.DeveloperProfileEntity", null)
                        .WithMany("Projects")
                        .HasForeignKey("DeveloperProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CVA.Infrastructure.Postgres.UserEntity", b =>
                {
                    b.OwnsMany("CVA.Infrastructure.Postgres.WorkEntity", "WorkExperience", b1 =>
                        {
                            b1.Property<Guid>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<string>>("Achievements")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("achievements");

                            b1.Property<string>("CompanyName")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("company_name");

                            b1.Property<string>("Description")
                                .HasColumnType("text")
                                .HasColumnName("description");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<string>("Location")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("location");

                            b1.Property<string>("Role")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("role");

                            b1.Property<DateOnly?>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.PrimitiveCollection<List<string>>("TechStack")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("tech_stack");

                            b1.Property<Guid>("user_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("user_id");

                            b1.ToTable("works", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("user_id");
                        });

                    b.Navigation("WorkExperience");
                });

            modelBuilder.Entity("CVA.Infrastructure.Postgres.WorkExperienceEntity", b =>
                {
                    b.HasOne("CVA.Infrastructure.Postgres.DeveloperProfileEntity", null)
                        .WithMany("WorkExperience")
                        .HasForeignKey("DeveloperProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CVA.Infrastructure.Postgres.LocationEntity", "Location", b1 =>
                        {
                            b1.Property<Guid>("WorkExperienceEntityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("country");

                            b1.HasKey("WorkExperienceEntityId");

                            b1.ToTable("work_experiences");

                            b1.WithOwner()
                                .HasForeignKey("WorkExperienceEntityId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CVA.Infrastructure.Postgres.DeveloperProfileEntity", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("WorkExperience");
                });
#pragma warning restore 612, 618
        }
    }
}
